{
 "title": "Dashboard-Demo-Pushgateway",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up_all", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Top 15 CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 11 },
   "targets": [
    { "expr": "topk(15, cpu_prdall)", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Top 15 Memory",
   "type": "stat",
   "gridPos": { "h": 12, "w": 9, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(15, mem_prdall)", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "FS >= 90%",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  }
 ]
}